### ISSUE TITLE
Je ne comprends pas

### ISSUE THREAD

**Issue by jpgdev** [harley1011/COMP346_ASSIGNMENT3#2]
Bonjour,

J'aimerais comprendre ce projet, mais il est en anglais. J'aimerais qu'il soit traduit en français considérant qu'on est au Québec.

[Problème relié](https://github.com/jpgdev/TP3-IMN428/issues/1)

Merci.

**Comment by bob827** [comment]
+1

**Comment by harley1011** [comment]
Sorry, I don't speak Spanish.

**Comment by alexnault** [comment]
Why is spanish? Yuo of change to russian for fear of mother russia.
